spring:
  application:
    name: task-srv
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    data: classpath:/data-trans.sql
    url: jdbc:h2:mem:taskTest
    driver-class-name: org.h2.Driver
    password:
    username: sa
    initialization-mode: always



management:
  security:
    enabled: false
  server:
    port: 8082
  endpoints:
    web:
      base-path: ${server.servlet.context-path}/management
      exposure:
        include: '*'

server:
  port: 8081
  servlet:
    context-path: /task-srv

springfox:
  documentation:
    swagger:
      v2:
        path: ${server.servlet.context-path}/v2/api-docs

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

---
spring:
  profiles: tests
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      write_dates_as_timestamps: false